from alemanpyutils.function.function import Function
from alemanpyutils.function.identity_function import IdentityFunction
from alemanpyutils.function.to_upper_case_function import ToUpperCaseFunction
